// water_erp_web/supplier-vue/src/views/bid/Archive.vue
<script setup>
import { computed } from 'vue'
import { ElMessage } from 'element-plus'
import { Box, CircleCheck, Warning } from '@element-plus/icons-vue'
import { useBidStore } from '@/stores/bid'

const bidStore = useBidStore()
const archiveRate = computed(() => Math.round((bidStore.archiveItems.filter(item => item.status === '已归档').length / bidStore.archiveItems.length) * 100))
const archiveAll = () => {
  bidStore.markArchiveComplete()
  ElMessage.success('资料已完成一键归档演示，防篡改摘要已更新。')
}
</script>

<template>
  <div class="page-container archive-page">
    <div class="page-header"><h1 class="page-title">归档端</h1><p class="page-subtitle">开标记录、评分表、澄清记录、评标报告、结果公示统一归档</p></div>

    <div class="archive-summary content-card">
      <el-icon><Box /></el-icon>
      <div><h2>电子档案编号：ARCH-BID-2026-0518</h2><p>防篡改摘要：HASH-CHAIN-20260608-AF39C8E2</p></div>
      <el-progress type="circle" :percentage="archiveRate" />
      <el-button type="success" @click="archiveAll">一键归档演示</el-button>
    </div>

    <div class="archive-grid">
      <div class="content-card">
        <div class="card-header"><h2 class="card-title">归档资料清单</h2></div>
        <el-table :data="bidStore.archiveItems" border>
          <el-table-column prop="name" label="资料名称" min-width="180" />
          <el-table-column prop="owner" label="责任端" width="130" />
          <el-table-column prop="status" label="状态" width="110">
            <template #default="{ row }"><el-tag :type="row.status === '已归档' ? 'success' : row.status === '待确认' ? 'warning' : 'info'">{{ row.status }}</el-tag></template>
          </el-table-column>
          <el-table-column prop="hash" label="哈希摘要" width="150" />
          <el-table-column prop="time" label="归档时间" width="165" />
        </el-table>
      </div>

      <div class="content-card">
        <div class="card-header"><h2 class="card-title">缺失提醒</h2></div>
        <p class="archive-tip"><el-icon><Warning /></el-icon> 专家评分汇总表待归档。</p>
        <p class="archive-tip"><el-icon><Warning /></el-icon> 评标报告待专家最终确认。</p>
        <p class="archive-tip success"><el-icon><CircleCheck /></el-icon> 开标记录、投标回执和下载日志已入档。</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.page-container { padding: 24px; background: #f6f9fd; min-height: calc(100vh - 60px); }
.page-header { margin-bottom: 24px; }
.page-title { font-size: 22px; font-weight: 800; color: #18243a; margin: 0 0 8px; }
.page-subtitle { font-size: 14px; color: #8a9aaa; margin: 0; }
.content-card { background: #fff; border: 1px solid #e8f0fa; border-radius: 8px; padding: 20px; margin-bottom: 16px; }
.card-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 18px; }
.card-title { font-size: 17px; font-weight: 800; color: #18243a; margin: 0; }
.archive-summary { display: grid; grid-template-columns: 56px 1fr 120px auto; align-items: center; gap: 18px; }
.archive-summary > .el-icon { font-size: 40px; color: #064ea2; }
.archive-summary h2 { margin: 0 0 6px; font-size: 16px; color: #18243a; }
.archive-summary p { color: #8a9aaa; margin: 0; }
.archive-grid { display: grid; grid-template-columns: 1.4fr .7fr; gap: 16px; }
.archive-tip { display: flex; align-items: center; gap: 8px; padding: 12px; border-radius: 8px; background: #fff8e8; color: #536078; margin: 0 0 10px; font-size: 13px; }
.archive-tip .el-icon { color: #f5a623; }
.archive-tip.success { background: #e8fff0; }
.archive-tip.success .el-icon { color: #11a874; }
@media (max-width: 1000px) { .archive-summary, .archive-grid { grid-template-columns: 1fr; } }
</style>

// water-erp/apps/web/src/app/(dashboard)/bid/archive/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import type { BidProjectDetail } from '@/lib/types';

export default function BidArchivePage() {
  const [project, setProject] = useState<BidProjectDetail | null>(null);

  const load = () => {
    api.get<BidProjectDetail[]>('/bid/projects').then(ps => {
      if (ps.length) api.get<BidProjectDetail>(`/bid/projects/${ps[0].id}`).then(setProject);
    });
  };

  useEffect(() => { load(); }, []);

  if (!project) return <div className="text-[#5a6d8a]">加载中...</div>;

  const archived = project.archiveItems.filter(a => a.status === 'ARCHIVED').length;
  const rate = Math.round((archived / project.archiveItems.length) * 100);
  const statusLabel: Record<string, string> = { ARCHIVED: '已归档', PENDING_CONFIRM: '待确认', NOT_STARTED: '未开始' };
  const statusColor: Record<string, string> = { ARCHIVED: '#11a874', PENDING_CONFIRM: '#f5a623', NOT_STARTED: '#8a9aaa' };

  return (
    <div>
      <h1 className="text-2xl font-bold text-[#18243a] mb-1">归档端</h1>
      <p className="text-sm text-[#5a6d8a] mb-6">开标记录、评分表、澄清记录、评标报告、结果公示统一归档</p>

      <div className="bg-white rounded-xl border border-[#e8f0fa] p-5 mb-4 flex items-center gap-6">
        <div className="text-4xl">📦</div>
        <div><h2 className="font-bold text-[#18243a]">电子档案编号：ARCH-{project.projectCode}</h2><p className="text-sm text-[#5a6d8a]">防篡改摘要：HASH-CHAIN-20260608-AF39C8E2</p></div>
        <div className="text-center"><div className="text-3xl font-bold text-[#064ea2]">{rate}%</div><div className="text-xs text-[#5a6d8a]">归档完整率</div></div>
        <button onClick={async () => { if(project) { await api.post(`/bid/projects/${project.id}/archive-all`, {}); load(); }}}
          className="px-5 py-2 bg-[#11a874] text-white rounded-lg font-semibold hover:bg-[#0e8f62] transition">一键归档演示</button>
      </div>

      <div className="grid grid-cols-[1.4fr_0.7fr] gap-4">
        <div className="bg-white rounded-xl border border-[#e8f0fa] p-5">
          <h2 className="font-bold text-[#18243a] mb-3">归档资料清单</h2>
          <table className="w-full text-sm">
            <thead><tr className="border-b border-[#e8f0fa] text-left text-[#5a6d8a]"><th className="pb-2">资料名称</th><th className="pb-2">责任端</th><th className="pb-2">状态</th><th className="pb-2">哈希摘要</th></tr></thead>
            <tbody>{project.archiveItems.map(a => (
              <tr key={a.id} className="border-b border-[#e8f0fa]">
                <td className="py-2">{a.name}</td><td className="py-2 text-[#5a6d8a]">{a.ownerRole}</td>
                <td className="py-2"><span className="px-2 py-0.5 rounded text-xs font-semibold" style={{ color: statusColor[a.status], backgroundColor: statusColor[a.status] + '18' }}>{statusLabel[a.status]}</span></td>
                <td className="py-2 text-[#5a6d8a] font-mono text-xs">{a.hashDigest || '—'}</td>
              </tr>
            ))}</tbody>
          </table>
        </div>
        <div className="bg-white rounded-xl border border-[#e8f0fa] p-5">
          <h2 className="font-bold text-[#18243a] mb-3">缺失提醒</h2>
          {project.archiveItems.filter(a => a.status !== 'ARCHIVED').map(a => (
            <div key={a.id} className="bg-[#fff8e8] rounded-lg p-3 text-sm text-[#8a6d3b] mb-2">⚠️ {a.name}{a.status === 'PENDING_CONFIRM' ? '待确认' : '未开始'}</div>
          ))}
          {project.archiveItems.filter(a => a.status === 'ARCHIVED').length > 0 && (
            <div className="bg-[#e8fff0] rounded-lg p-3 text-sm text-[#0e8f62]">✅ {project.archiveItems.filter(a => a.status === 'ARCHIVED').map(a => a.name).join('、')}已入档</div>
          )}
        </div>
      </div>
    </div>
  );
}
