// water-erp/apps/supplier-portal/src/views/bid/OpeningConfirm.vue
<script setup lang="ts">
// 旧入口兼容：开标确认已并入「在线开标大厅」页
import { onMounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
const route = useRoute()
const router = useRouter()
onMounted(() => {
  router.replace(`/my-bids/${route.params.projectId}/opening-hall`)
})
</script>

<template>
  <div style="padding: 40px; text-align: center; color: #909399">正在进入在线开标大厅…</div>
</template>

// water-erp/apps/supplier-portal-next/src/app/(main)/my-bids/[projectId]/opening-confirm/page.tsx
"use client";

// 旧入口兼容：开标确认已并入「在线开标大厅」页（唱标记录查看/确认/异议全在 opening-hall）
import { useEffect } from "react";
import { useParams, useRouter } from "next/navigation";

export default function OpeningConfirmPage() {
  const params = useParams<{ projectId: string }>();
  const router = useRouter();

  useEffect(() => {
    router.replace(`/my-bids/${params.projectId}/opening-hall`);
  }, [params.projectId, router]);

  return <div style={{ padding: 40, textAlign: "center", color: "#909399" }}>正在进入在线开标大厅…</div>;
}
