// water-erp/apps/supplier-portal-next/src/components/countdown-timer.tsx
"use client";

import { useEffect, useState } from "react";
import { Clock, Timer, CircleX } from "lucide-react";

/**
 * 投递截止倒计时 — 移植自 Vue CountdownTimer.vue。
 * urgency：normal（>24h）/ urgent（<24h）/ critical（<1h，图标脉冲）/ expired（已截止）。
 * 样式 .sp-countdown / .pulse-icon 已在 globals.css。
 */
export function CountdownTimer({ deadline }: { deadline: string | Date }) {
  const [now, setNow] = useState(() => Date.now());

  useEffect(() => {
    const timer = setInterval(() => setNow(Date.now()), 1000);
    return () => clearInterval(timer);
  }, []);

  const diff = new Date(deadline).getTime() - now;
  const isExpired = diff <= 0;

  let display = "已截止";
  if (!isExpired) {
    const days = Math.floor(diff / 86400000);
    const hours = Math.floor((diff % 86400000) / 3600000);
    const mins = Math.floor((diff % 3600000) / 60000);
    const secs = Math.floor((diff % 60000) / 1000);
    if (days > 0) display = `${days}天 ${hours}时 ${mins}分`;
    else if (hours > 0) display = `${hours}时 ${mins}分 ${secs}秒`;
    else display = `${mins}分 ${secs}秒`;
  }

  const urgency = isExpired ? "expired" : diff / 3600000 < 1 ? "critical" : diff / 3600000 < 24 ? "urgent" : "normal";

  return (
    <span className={`sp-countdown ${urgency}`}>
      {urgency === "expired" ? (
        <CircleX size={13} />
      ) : urgency === "critical" ? (
        <Timer size={13} className="pulse-icon" />
      ) : (
        <Clock size={13} />
      )}
      {display}
    </span>
  );
}

// water-erp/apps/supplier-portal/src/components/CountdownTimer.vue
<script setup lang="ts">
import { ref, onMounted, onUnmounted, computed } from 'vue'

const props = defineProps<{ deadline: string | Date }>()

const now = ref(Date.now())
let timer: any = null

onMounted(() => {
  timer = setInterval(() => { now.value = Date.now() }, 1000)
})

onUnmounted(() => { if (timer) clearInterval(timer) })

const diff = computed(() => {
  const end = new Date(props.deadline).getTime()
  return end - now.value
})

const isExpired = computed(() => diff.value <= 0)

const display = computed(() => {
  if (isExpired.value) return '已截止'
  const d = diff.value
  const days = Math.floor(d / 86400000)
  const hours = Math.floor((d % 86400000) / 3600000)
  const mins = Math.floor((d % 3600000) / 60000)
  const secs = Math.floor((d % 60000) / 1000)
  if (days > 0) return `${days}天 ${hours}时 ${mins}分`
  if (hours > 0) return `${hours}时 ${mins}分 ${secs}秒`
  return `${mins}分 ${secs}秒`
})

const urgency = computed(() => {
  if (isExpired.value) return 'expired'
  const hours = diff.value / 3600000
  if (hours < 1) return 'critical'
  if (hours < 24) return 'urgent'
  return 'normal'
})
</script>

<template>
  <span class="sp-countdown" :class="urgency">
    <el-icon v-if="urgency === 'expired'"><CircleCloseFilled /></el-icon>
    <el-icon v-else-if="urgency === 'critical'" class="pulse-icon"><Timer /></el-icon>
    <el-icon v-else><Clock /></el-icon>
    {{ display }}
  </span>
</template>

<style scoped>
.sp-countdown {
  display: inline-flex;
  align-items: center;
  gap: 5px;
  font-size: 13px;
  font-weight: 700;
}

.sp-countdown.normal { color: var(--sp-gray-500); }
.sp-countdown.urgent { color: var(--sp-orange); }
.sp-countdown.critical { color: var(--sp-red); }
.sp-countdown.expired { color: var(--sp-gray-400); }

.pulse-icon {
  animation: pulse 1s ease-in-out infinite;
}

@keyframes pulse {
  0%, 100% { opacity: 1; }
  50% { opacity: 0.4; }
}
</style>
