// water-erp/apps/supplier-portal-next/src/app/(main)/bids/[id]/round-quote/page.tsx
"use client";

import { useEffect, useRef, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import dayjs from "dayjs";
import { toast } from "sonner";
import { AlertTriangle, ArrowLeft, CircleCheck, Coins, Inbox, Lock } from "lucide-react";
import { SpPageHero } from "@/components/sp-page-hero";
import { EmptyState, LoadingBlock, SpButton } from "@/components/ui";
import { bidApi } from "@/lib/api/bid";
import { ApiError } from "@/lib/api";
import { useBidWebSocket } from "@/hooks/use-bid-websocket";
import { useLeaveGuard } from "@/hooks/use-leave-guard";
import "@/styles/pages/opening.css";

interface Round {
  id: string;
  roundNo: number;
  roundType: string;
  status: string;
  deadline: string | null;
}
interface Quote {
  id: string;
  bidSupplierId: string;
  quotePrice: string;
  status: string;
}
interface MyQuote {
  id: string;
  roundId: string;
  quotePrice: string;
  submittedAt: string;
  status: string;
}

const statusLabels: Record<string, string> = {
  pending: "待开放",
  open: "报价中",
  sealed: "已截止",
  published: "已公布",
  closed: "已结束",
};
const statusColors: Record<string, string> = {
  pending: "#909399",
  open: "#409eff",
  sealed: "#e6a23c",
  published: "#67c23a",
  closed: "#909399",
};

function formatTime(iso: string | null): string {
  return iso ? dayjs(iso).format("MM-DD HH:mm") : "—";
}

function formatPrice(p: string | number): string {
  return Number(p).toLocaleString("zh-CN", { minimumFractionDigits: 2, maximumFractionDigits: 2 });
}

export default function RoundQuotePage() {
  const params = useParams<{ id: string }>();
  const router = useRouter();
  const projectId = params.id;

  const [loading, setLoading] = useState(true);
  const [rounds, setRounds] = useState<Round[]>([]);
  const [publishedQuotes, setPublishedQuotes] = useState<Record<string, Quote[]>>({});
  const [myQuotes, setMyQuotes] = useState<Record<string, MyQuote>>({}); // roundId → 我的报价
  const [myBidSupplierId, setMyBidSupplierId] = useState<string>("");
  const [quotePriceText, setQuotePriceText] = useState<string>(""); // el-input-number 的输入态
  const [submitting, setSubmitting] = useState(false);
  // M4: 客户端截止倒计时
  const [deadlinePassed, setDeadlinePassed] = useState(false);

  // el-input-number(min=0.01, precision=2) → 原生 number 输入 + parseFloat（空串视为未填）
  const quotePrice = quotePriceText.trim() === "" ? undefined : parseFloat(quotePriceText);
  const quotePriceValid = quotePrice != null && Number.isFinite(quotePrice);

  const currentOpenRound = rounds.find((r) => r.status === "open");
  const currentOpenMyQuote = currentOpenRound ? myQuotes[currentOpenRound.id] : undefined;

  // checkDeadline 由 10s 定时器触发，需读最新轮次——ref 镜像避免闭包过期
  const openRoundRef = useRef<Round | undefined>(currentOpenRound);
  openRoundRef.current = currentOpenRound;

  function checkDeadline() {
    const r = openRoundRef.current;
    if (!r?.deadline) {
      setDeadlinePassed(false);
      return;
    }
    setDeadlinePassed(new Date() > new Date(r.deadline));
  }

  // 轮次状态实时：开轮/封轮/发布结果（round:status:change）→ 重载轮次与报价
  // （handlers 为每渲染取最新闭包的 getter，fetchData 直接引用即可）
  useBidWebSocket(projectId, () => ({
    onRoundStatusChange: () => {
      fetchData().catch(() => {});
    },
  }));

  async function reloadMyQuotes() {
    try {
      const list = (await bidApi.getMyQuotes(projectId)) as MyQuote[];
      const map: Record<string, MyQuote> = {};
      for (const q of list ?? []) map[q.roundId] = q;
      setMyQuotes(map);
      return map;
    } catch {
      /* ignore */
    }
  }

  async function fetchData() {
    setLoading(true);
    try {
      const res = await bidApi.listRounds(projectId);
      const list = (res ?? []) as Round[];
      setRounds(list);

      // 获取当前供应商在此项目中的 BidSupplier ID
      try {
        const bs = await bidApi.getMyBidSupplier(projectId);
        setMyBidSupplierId(bs?.id ?? "");
      } catch {
        /* 非项目成员则保持为空 */
      }

      // 获取我的全部报价历史
      await reloadMyQuotes();

      // Load published round quotes
      for (const r of list) {
        if (r.status === "published" || r.status === "closed") {
          try {
            const q = (await bidApi.getRoundQuotes(projectId, r.id)) as Quote[];
            setPublishedQuotes((prev) => ({ ...prev, [r.id]: q }));
          } catch {
            /* ignore */
          }
        }
      }
    } catch {
      toast.error("加载失败");
    } finally {
      setLoading(false);
    }
  }

  useEffect(() => {
    fetchData();
    // M4: 每 10 秒检查截止时间
    const t = setInterval(checkDeadline, 10000);
    checkDeadline();
    return () => clearInterval(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  // L8: 输入价格后导航离开提示（Vue onBeforeRouteLeave → useLeaveGuard）
  useLeaveGuard(
    () => quotePriceValid && !submitting && !currentOpenMyQuote,
    "您已输入报价但尚未提交，确定离开吗？",
  );

  async function handleSubmit() {
    if (!currentOpenRound || !myBidSupplierId || !quotePriceValid) return;
    const price = Math.round(quotePrice! * 100) / 100; // precision=2

    // 提交前确认弹窗——提醒供应商仔细核对价格（ElMessageBox.confirm → 原生 confirm）
    const confirmed = window.confirm(
      `请确认您的报价金额：\n\n¥${formatPrice(price)}\n\n提交后不可修改，请确保价格准确无误。`,
    );
    if (!confirmed) return; // 用户取消

    setSubmitting(true);
    try {
      await bidApi.submitQuote(projectId, currentOpenRound.id, {
        bidSupplierId: myBidSupplierId,
        quotePrice: price,
      });
      toast.success("报价已提交(密封)，不可修改");
      setQuotePriceText("");
      // 刷新我的报价状态
      await reloadMyQuotes();
    } catch (e: any) {
      // L4: P2002 唯一约束冲突（双 tab 并发）或后端 ALREADY_QUOTED → 友好提示
      const errMsg =
        e instanceof ApiError ? ((e.data as any)?.error ?? e.code) : undefined;
      if (errMsg === "ALREADY_QUOTED" || (e instanceof ApiError && e.status === 400)) {
        toast.warning("本轮已提交报价，不可重复提交");
      } else {
        toast.error(errMsg || "提交失败");
      }
    } finally {
      setSubmitting(false);
    }
  }

  return (
    <div>
      {/* 注：Vue 版传的是未声明的 subtitle prop（实际不渲染）；此处按组件契约传 sub 以呈现设计意图 */}
      <SpPageHero icon={Coins} title="多轮报价" sub="密封报价 · 谈判/竞价采购" />

      <div className="mx-auto max-w-3xl p-6">
        <div className="mb-4">
          <SpButton variant="link" icon={ArrowLeft} onClick={() => router.back()}>
            返回
          </SpButton>
        </div>

        {!loading && rounds.length === 0 ? (
          <EmptyState icon={Inbox} title="暂无报价轮次" />
        ) : (
          <div className="space-y-4">
            {loading && rounds.length === 0 && <LoadingBlock />}

            {/* 当前开放轮次 */}
            {currentOpenRound && (
              <section className="rq-card rq-card--open">
                <header className="rq-card__header">
                  <div className="flex items-center justify-between">
                    <span className="font-bold">第 {currentOpenRound.roundNo} 轮报价</span>
                    <span className="rq-tag">{statusLabels[currentOpenRound.status]}</span>
                  </div>
                </header>

                <div className="rq-card__body">
                  {currentOpenRound.deadline && (
                    <div className="mb-4 text-sm text-gray-500">截止时间: {formatTime(currentOpenRound.deadline)}</div>
                  )}

                  {/* 已提交：锁定状态 */}
                  {currentOpenMyQuote ? (
                    <div className="rq-alert rq-alert--success mb-2">
                      <CircleCheck size={16} className="shrink-0" />
                      <div className="flex w-full items-center justify-between">
                        <span className="text-sm">
                          已提交报价：<strong className="font-mono text-base">¥{formatPrice(currentOpenMyQuote.quotePrice)}</strong>
                          {" · "}
                          {formatTime(currentOpenMyQuote.submittedAt)}
                        </span>
                        <span className="rq-tag rq-tag--sm rq-tag--info-plain">已锁定 · 不可修改</span>
                      </div>
                    </div>
                  ) : (
                    <>
                      {/* 未提交：报价输入 */}
                      <div className="rq-alert rq-alert--warning mb-4">
                        <AlertTriangle size={16} className="shrink-0" />
                        <span className="text-sm">报价提交后不可修改，请仔细核对金额后再提交。</span>
                      </div>

                      <div className="mb-4 flex items-center gap-4">
                        <label className="text-sm" style={{ width: 100, textAlign: "right" }}>
                          报价(元)
                        </label>
                        <input
                          type="number"
                          className="rq-input-number"
                          min={0.01}
                          step={0.01}
                          placeholder="请输入报价金额"
                          value={quotePriceText}
                          onChange={(e) => setQuotePriceText(e.target.value)}
                        />
                      </div>

                      <div className="flex justify-end">
                        <SpButton
                          variant="primary"
                          icon={Lock}
                          loading={submitting}
                          disabled={!quotePriceValid || deadlinePassed}
                          onClick={handleSubmit}
                        >
                          提交密封报价
                        </SpButton>
                      </div>
                    </>
                  )}
                </div>
              </section>
            )}

            {/* 各轮次状态 */}
            {rounds.map((r) => (
              <section key={r.id} className="rq-card rq-card--plain">
                <div className="flex items-center justify-between">
                  <div className="flex items-center gap-2">
                    <span className="rounded bg-blue-100 px-2 py-0.5 text-xs font-bold text-blue-700">第 {r.roundNo} 轮</span>
                    <span
                      className="rq-tag rq-tag--sm"
                      style={statusColors[r.status] ? { color: statusColors[r.status], borderColor: statusColors[r.status] } : undefined}
                    >
                      {statusLabels[r.status]}
                    </span>
                    {r.deadline && <span className="text-xs text-gray-400">截止 {formatTime(r.deadline)}</span>}
                  </div>
                  {/* sealed 轮次：已提交标记 */}
                  {r.status === "sealed" && myQuotes[r.id] && (
                    <span className="flex items-center gap-1 text-xs text-amber-600">
                      <Lock size={14} /> 已提交（密封中）
                    </span>
                  )}
                </div>

                {/* 已公布轮次: 报价排名 */}
                {(r.status === "published" || r.status === "closed") && publishedQuotes[r.id]?.length ? (
                  <div className="mt-3">
                    <div className="overflow-hidden rounded-lg border border-gray-100">
                      <table className="w-full text-sm">
                        <thead>
                          <tr className="bg-gray-50 text-xs text-gray-500">
                            <th className="px-3 py-2 text-left font-semibold">排名</th>
                            <th className="px-3 py-2 text-left font-semibold">供应商</th>
                            <th className="px-3 py-2 text-right font-semibold">报价(元)</th>
                          </tr>
                        </thead>
                        <tbody>
                          {publishedQuotes[r.id].map((q, idx) => (
                            <tr
                              key={q.id}
                              className={`border-t border-gray-100${q.bidSupplierId === myBidSupplierId ? " bg-blue-50" : ""}`}
                            >
                              <td className="px-3 py-2 font-mono font-bold text-blue-600">{idx + 1}</td>
                              <td className={`px-3 py-2 font-medium${q.bidSupplierId === myBidSupplierId ? " text-blue-700" : ""}`}>
                                {q.bidSupplierId === myBidSupplierId ? "本企业" : "其他供应商"}
                              </td>
                              <td className="px-3 py-2 text-right font-mono font-semibold">{formatPrice(q.quotePrice)}</td>
                            </tr>
                          ))}
                        </tbody>
                      </table>
                    </div>
                  </div>
                ) : null}
              </section>
            ))}
          </div>
        )}
      </div>
    </div>
  );
}

// water-erp/apps/supplier-portal/src/views/bid/RoundQuote.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRoute, useRouter, onBeforeRouteLeave } from 'vue-router'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ArrowLeft, Coin, Lock } from '@element-plus/icons-vue'
import SpPageHero from '@/components/SpPageHero.vue'
import { bidApi } from '@/api/bid'
import { useBidWebSocket } from '@/composables/useBidWebSocket'
import dayjs from 'dayjs'

const route = useRoute()
const router = useRouter()
const projectId = route.params.id as string

// 轮次状态实时：开轮/封轮/发布结果（round:status:change）→ 重载轮次与报价
useBidWebSocket(projectId, {
  onRoundStatusChange: () => { fetchData().catch(() => {}) },
})

interface Round {
  id: string; roundNo: number; roundType: string; status: string; deadline: string | null
}
interface Quote { id: string; bidSupplierId: string; quotePrice: string; status: string }
interface MyQuote { id: string; roundId: string; quotePrice: string; submittedAt: string; status: string }

const loading = ref(true)
const rounds = ref<Round[]>([])
const publishedQuotes = ref<Record<string, Quote[]>>({})
const myQuotes = ref<Record<string, MyQuote>>({}) // roundId → 我的报价
const myBidSupplierId = ref<string>('')
const quotePrice = ref<number | undefined>(undefined)
const submitting = ref(false)
// M4: 客户端截止倒计时
const deadlinePassed = ref(false)
let deadlineTimer: ReturnType<typeof setInterval> | null = null

function checkDeadline() {
  if (!currentOpenRound.value?.deadline) { deadlinePassed.value = false; return }
  deadlinePassed.value = new Date() > new Date(currentOpenRound.value.deadline)
}

const currentOpenRound = computed(() => rounds.value.find(r => r.status === 'open'))
const currentOpenMyQuote = computed(() => currentOpenRound.value ? myQuotes.value[currentOpenRound.value.id] : undefined)

async function fetchData() {
  loading.value = true
  try {
    const res = await bidApi.listRounds(projectId)
    rounds.value = res as any

    // 获取当前供应商在此项目中的 BidSupplier ID
    try {
      const bsRes = await bidApi.getMyBidSupplier(projectId)
      myBidSupplierId.value = (bsRes as any)?.id ?? ''
    } catch (e) { /* 非项目成员则保持为空 */ }

    // 获取我的全部报价历史
    try {
      const mqRes = await bidApi.getMyQuotes(projectId)
      const list = (mqRes as any) as MyQuote[]
      const map: Record<string, MyQuote> = {}
      for (const q of list) map[q.roundId] = q
      myQuotes.value = map
    } catch (e) { /* ignore */ }

    // Load published round quotes
    for (const r of rounds.value) {
      if (r.status === 'published' || r.status === 'closed') {
        try {
          const qRes = await bidApi.getRoundQuotes(projectId, r.id)
          publishedQuotes.value[r.id] = qRes as any
        } catch (e) { /* ignore */ }
      }
    }
  } catch (e) {
    ElMessage.error('加载失败')
  } finally {
    loading.value = false
  }
}

async function handleSubmit() {
  if (!currentOpenRound.value || !myBidSupplierId.value || quotePrice.value == null) return

  // 提交前确认弹窗——提醒供应商仔细核对价格
  try {
    await ElMessageBox.confirm(
      `请确认您的报价金额：\n\n¥${formatPrice(quotePrice.value)}\n\n提交后不可修改，请确保价格准确无误。`,
      '报价确认',
      {
        confirmButtonText: '确认提交',
        cancelButtonText: '再检查一下',
        type: 'warning',
        distinguishCancelAndClose: true,
      },
    )
  } catch {
    return // 用户取消
  }

  submitting.value = true
  try {
    await bidApi.submitQuote(projectId, currentOpenRound.value.id, {
      bidSupplierId: myBidSupplierId.value,
      quotePrice: quotePrice.value,
    })
    ElMessage.success('报价已提交(密封)，不可修改')
    quotePrice.value = undefined
    // 刷新我的报价状态
    const mqRes = await bidApi.getMyQuotes(projectId)
    const list = (mqRes as any) as MyQuote[]
    const map: Record<string, MyQuote> = {}
    for (const q of list) map[q.roundId] = q
    myQuotes.value = map
  } catch (e: any) {
    // L4: P2002 唯一约束冲突（双 tab 并发）或后端 ALREADY_QUOTED → 友好提示
    const errMsg = e?.response?.data?.error || e?.response?.data?.code
    if (errMsg === 'ALREADY_QUOTED' || e?.response?.status === 400) {
      ElMessage.warning('本轮已提交报价，不可重复提交')
    } else {
      ElMessage.error(errMsg || '提交失败')
    }
  } finally {
    submitting.value = false
  }
}

function formatTime(iso: string | null): string {
  return iso ? dayjs(iso).format('MM-DD HH:mm') : '—'
}

function formatPrice(p: string | number): string {
  return Number(p).toLocaleString('zh-CN', { minimumFractionDigits: 2, maximumFractionDigits: 2 })
}

const statusLabels: Record<string, string> = {
  pending: '待开放', open: '报价中', sealed: '已截止', published: '已公布', closed: '已结束',
}
const statusColors: Record<string, string> = {
  pending: '#909399', open: '#409eff', sealed: '#e6a23c', published: '#67c23a', closed: '#909399',
}

onMounted(() => {
  fetchData()
  // M4: 每 10 秒检查截止时间
  deadlineTimer = setInterval(checkDeadline, 10000)
  checkDeadline()
})
onUnmounted(() => { if (deadlineTimer) clearInterval(deadlineTimer) })

// L8: 输入价格后导航离开提示
onBeforeRouteLeave(() => {
  if (quotePrice.value != null && !submitting.value && !currentOpenMyQuote.value) {
    return window.confirm('您已输入报价但尚未提交，确定离开吗？')
  }
})
</script>

<template>
  <div>
    <SpPageHero title="多轮报价" subtitle="密封报价 · 谈判/竞价采购" :icon="Coin" />

    <div class="mx-auto max-w-3xl p-6">
      <div class="mb-4">
        <el-button :icon="ArrowLeft" text @click="router.back()">返回</el-button>
      </div>

      <el-empty v-if="!loading && rounds.length === 0" description="暂无报价轮次" />

      <div v-else class="space-y-4">
        <!-- 当前开放轮次 -->
        <el-card v-if="currentOpenRound" shadow="hover">
          <template #header>
            <div class="flex items-center justify-between">
              <span class="font-bold">第 {{ currentOpenRound.roundNo }} 轮报价</span>
              <el-tag type="primary">{{ statusLabels[currentOpenRound.status] }}</el-tag>
            </div>
          </template>

          <div v-if="currentOpenRound.deadline" class="mb-4 text-sm text-gray-500">
            截止时间: {{ formatTime(currentOpenRound.deadline) }}
          </div>

          <!-- 已提交：锁定状态 -->
          <el-alert
            v-if="currentOpenMyQuote"
            type="success" :closable="false" class="mb-2"
            show-icon
          >
            <template #title>
              <div class="flex items-center justify-between">
                <span class="text-sm">
                  已提交报价：<strong class="font-mono text-base">¥{{ formatPrice(currentOpenMyQuote.quotePrice) }}</strong>
                  · {{ formatTime(currentOpenMyQuote.submittedAt) }}
                </span>
                <el-tag size="small" type="info" effect="plain">已锁定 · 不可修改</el-tag>
              </div>
            </template>
          </el-alert>

          <!-- 未提交：报价输入 -->
          <template v-else>
            <el-alert
              type="warning" :closable="false" class="mb-4"
              show-icon
            >
              <template #title>
                <span class="text-sm">报价提交后不可修改，请仔细核对金额后再提交。</span>
              </template>
            </el-alert>

            <el-form label-width="100px">
              <el-form-item label="报价(元)">
                <el-input-number
                  v-model="quotePrice"
                  :min="0.01"
                  :precision="2"
                  placeholder="请输入报价金额"
                  class="!w-64"
                />
              </el-form-item>
            </el-form>

            <div class="flex justify-end">
              <el-button
                type="primary" :icon="Lock" :loading="submitting"
                :disabled="quotePrice == null || deadlinePassed"
                @click="handleSubmit"
              >
                提交密封报价
              </el-button>
            </div>
          </template>
        </el-card>

        <!-- 各轮次状态 -->
        <el-card v-for="r in rounds" :key="r.id" shadow="never" class="!border-gray-200">
          <div class="flex items-center justify-between">
            <div class="flex items-center gap-2">
              <span class="rounded bg-blue-100 px-2 py-0.5 text-xs font-bold text-blue-700">第 {{ r.roundNo }} 轮</span>
              <el-tag size="small" :style="{ color: statusColors[r.status], borderColor: statusColors[r.status] }">
                {{ statusLabels[r.status] }}
              </el-tag>
              <span v-if="r.deadline" class="text-xs text-gray-400">截止 {{ formatTime(r.deadline) }}</span>
            </div>
            <!-- sealed 轮次：已提交标记 -->
            <span v-if="r.status === 'sealed' && myQuotes[r.id]" class="flex items-center gap-1 text-xs text-amber-600">
              <el-icon><Lock /></el-icon> 已提交（密封中）
            </span>
          </div>

          <!-- 已公布轮次: 报价排名 -->
          <div v-if="(r.status === 'published' || r.status === 'closed') && publishedQuotes[r.id]?.length" class="mt-3">
            <div class="overflow-hidden rounded-lg border border-gray-100">
              <table class="w-full text-sm">
                <thead>
                  <tr class="bg-gray-50 text-xs text-gray-500">
                    <th class="px-3 py-2 text-left font-semibold">排名</th>
                    <th class="px-3 py-2 text-left font-semibold">供应商</th>
                    <th class="px-3 py-2 text-right font-semibold">报价(元)</th>
                  </tr>
                </thead>
                <tbody>
                  <tr
                    v-for="(q, idx) in publishedQuotes[r.id]" :key="q.id"
                    class="border-t border-gray-100"
                    :class="q.bidSupplierId === myBidSupplierId ? 'bg-blue-50' : ''"
                  >
                    <td class="px-3 py-2 font-mono font-bold text-blue-600">{{ idx + 1 }}</td>
                    <td class="px-3 py-2 font-medium" :class="q.bidSupplierId === myBidSupplierId ? 'text-blue-700' : ''">
                      {{ q.bidSupplierId === myBidSupplierId ? '本企业' : '其他供应商' }}
                    </td>
                    <td class="px-3 py-2 text-right font-mono font-semibold">{{ formatPrice(q.quotePrice) }}</td>
                  </tr>
                </tbody>
              </table>
            </div>
          </div>
        </el-card>
      </div>
    </div>
  </div>
</template>
