// water-erp/apps/web/src/app/(dashboard)/bid/open/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import type { BidProjectDetail } from '@/lib/types';

export default function BidOpenPage() {
  const [project, setProject] = useState<BidProjectDetail | null>(null);

  useEffect(() => {
    api.get<BidProjectDetail[]>('/bid/projects').then(ps => {
      if (ps.length) api.get<BidProjectDetail>(`/bid/projects/${ps[0].id}`).then(setProject);
    });
  }, []);

  if (!project) return <div className="text-[#5a6d8a]">加载中...</div>;

  const session = project.openingSession;
  const decryptLabel: Record<string, string> = { PENDING: '待解密', RUNNING: '解密中', SUCCESS: '解密成功', DANGER: '异常' };
  const decryptColor: Record<string, string> = { PENDING: '#f5a623', RUNNING: '#064ea2', SUCCESS: '#11a874', DANGER: '#e74c3c' };

  return (
    <div>
      <h1 className="text-2xl font-bold text-[#18243a] mb-1">在线开标大厅</h1>
      <p className="text-sm text-[#5a6d8a] mb-6">到时自动提取投标文件，提示投标人在线解密，生成开标记录</p>

      {session && (
        <div className="bg-gradient-to-r from-[#063f82] to-[#0a7ed3] text-white rounded-xl p-6 mb-4 flex items-center gap-6">
          <div className="text-4xl">⚖️</div>
          <div className="flex-1">
            <h2 className="text-xl font-bold mb-1">{project.name}</h2>
            <p className="text-white/80 text-sm">开标时间：{new Date(project.openTime).toLocaleString('zh-CN')} ｜ 主持人：{session.host} ｜ 监督人：{session.supervisor}</p>
          </div>
          <div className="bg-white/15 rounded-lg p-4 text-center"><span className="text-xs text-white/80">状态</span><div className="text-lg font-bold">{session.status}</div></div>
        </div>
      )}

      <div className="bg-white rounded-xl border border-[#e8f0fa] p-5 mb-4">
        <h2 className="font-bold text-[#18243a] mb-3">投标人在线解密状态</h2>
        <table className="w-full text-sm">
          <thead><tr className="border-b border-[#e8f0fa] text-left text-[#5a6d8a]"><th className="pb-2">投标单位</th><th className="pb-2">投标回执</th><th className="pb-2">密文状态</th><th className="pb-2">解密状态</th><th className="pb-2">确认状态</th></tr></thead>
          <tbody>{project.suppliers.map(s => (
            <tr key={s.id} className="border-b border-[#e8f0fa]">
              <td className="py-2">{s.supplierName}</td>
              <td className="py-2 text-[#064ea2]">{s.receiptNo}</td>
              <td className="py-2">{s.encryptStatus}</td>
              <td className="py-2"><span className="px-2 py-0.5 rounded text-xs font-semibold" style={{ color: decryptColor[s.decryptStatus], backgroundColor: decryptColor[s.decryptStatus] + '18' }}>{decryptLabel[s.decryptStatus]}</span></td>
              <td className="py-2 text-[#5a6d8a]">{s.confirmStatus === 'CONFIRMED' ? '已确认' : s.confirmStatus === 'EXCEPTION' ? '异常待处理' : '待确认'}</td>
            </tr>
          ))}</tbody>
        </table>
      </div>

      <div className="bg-white rounded-xl border border-[#e8f0fa] p-5">
        <h2 className="font-bold text-[#18243a] mb-3">开标记录</h2>
        <table className="w-full text-sm">
          <thead><tr className="border-b border-[#e8f0fa] text-left text-[#5a6d8a]"><th className="pb-2">供应商</th><th className="pb-2">报价</th><th className="pb-2">工期</th><th className="pb-2">质量</th><th className="pb-2">保证金</th><th className="pb-2">确认</th></tr></thead>
          <tbody>{project.openingRecords.map((r, i) => (
            <tr key={i} className="border-b border-[#e8f0fa]"><td className="py-2">{r.supplierName}</td><td className="py-2 font-semibold">{r.amount}</td><td className="py-2">{r.period}</td><td className="py-2">{r.qualityTarget}</td><td className="py-2">{r.bondStatus}</td><td className="py-2">{r.confirmStatus}</td></tr>
          ))}</tbody>
        </table>
      </div>
    </div>
  );
}

// water_erp_web/supplier-vue/src/views/bid/Open.vue
<script setup>
import { ElMessage } from 'element-plus'
import { FolderOpened, Bell, DocumentChecked, Warning } from '@element-plus/icons-vue'
import { useBidStore } from '@/stores/bid'

const bidStore = useBidStore()
const decryptType = status => ({ success: 'success', running: 'primary', danger: 'danger', pending: 'warning' }[status] || 'info')
const decryptLabel = status => ({ success: '解密成功', running: '解密中', danger: '异常', pending: '待解密' }[status] || '未知')
const notify = () => ElMessage.success('已向待解密供应商发送在线解密提醒。')
const record = () => ElMessage.success('开标记录已生成并写入监督日志。')
</script>

<template>
  <div class="page-container open-page">
    <div class="page-header"><h1 class="page-title">在线开标大厅</h1><p class="page-subtitle">到时自动提取投标文件，提示投标人在线解密，生成开标记录</p></div>

    <div class="opening-hero content-card">
      <div><el-icon><FolderOpened /></el-icon></div>
      <section>
        <h2>{{ bidStore.projects[0].name }}</h2>
        <p>开标时间：{{ bidStore.projects[0].openTime }} ｜ 解密窗口：{{ bidStore.openingSession.decryptWindow }}</p>
        <p>主持人：{{ bidStore.openingSession.host }} ｜ 监督人：{{ bidStore.openingSession.supervisor }}</p>
      </section>
      <aside><span>剩余时间</span><strong>{{ bidStore.openingSession.remaining }}</strong><el-tag type="primary">{{ bidStore.openingSession.status }}</el-tag></aside>
    </div>

    <div class="action-row">
      <el-button type="primary" @click="notify"><el-icon><Bell /></el-icon>发送解密提醒</el-button>
      <el-button type="success" @click="record"><el-icon><DocumentChecked /></el-icon>生成开标记录</el-button>
    </div>

    <div class="content-card">
      <div class="card-header"><h2 class="card-title">投标人在线解密状态</h2></div>
      <el-table :data="bidStore.suppliers" border>
        <el-table-column prop="name" label="投标单位" min-width="220" />
        <el-table-column prop="receipt" label="投标回执" width="160" />
        <el-table-column prop="encrypt" label="密文状态" width="130" />
        <el-table-column label="解密状态" width="120"><template #default="{ row }"><el-tag :type="decryptType(row.decrypt)">{{ decryptLabel(row.decrypt) }}</el-tag></template></el-table-column>
        <el-table-column prop="confirm" label="确认状态" width="130" />
      </el-table>
    </div>

    <div class="open-grid">
      <div class="content-card">
        <div class="card-header"><h2 class="card-title">开标记录</h2></div>
        <el-table :data="bidStore.openingRecords" border>
          <el-table-column prop="supplier" label="供应商" min-width="200" />
          <el-table-column prop="amount" label="报价" width="120" />
          <el-table-column prop="period" label="工期/服务期" width="120" />
          <el-table-column prop="quality" label="质量目标" width="100" />
          <el-table-column prop="bond" label="保证金" width="100" />
          <el-table-column prop="confirm" label="确认" width="100" />
        </el-table>
      </div>
      <div class="content-card exception-card">
        <div class="card-header"><h2 class="card-title">异常处理</h2><el-icon class="text-warning"><Warning /></el-icon></div>
        <p><strong>四川宏达水利工程有限公司：</strong>证书校验失败，初步判定为投标人原因。</p>
        <p><strong>处理意见：</strong>保留插件日志、证书校验截图、在线提醒记录，提交监督端确认。</p>
      </div>
    </div>
  </div>
</template>

<style scoped>
.page-container { padding: 24px; background: #f6f9fd; min-height: calc(100vh - 60px); }
.page-header { margin-bottom: 24px; }
.page-title { font-size: 22px; font-weight: 800; color: #18243a; margin: 0 0 8px; }
.page-subtitle { font-size: 14px; color: #8a9aaa; margin: 0; }
.content-card { background: #fff; border: 1px solid #e8f0fa; border-radius: 8px; padding: 20px; margin-bottom: 16px; }
.card-header { display: flex; justify-content: space-between; align-items: center; margin-bottom: 18px; }
.card-title { font-size: 17px; font-weight: 800; color: #18243a; margin: 0; }
.text-warning { color: #f5a623; }
.opening-hero { display: grid; grid-template-columns: 72px 1fr 180px; align-items: center; gap: 18px; background: linear-gradient(135deg, #063f82, #0a7ed3); color: #fff; border: none; }
.opening-hero .el-icon { font-size: 46px; }
.opening-hero h2 { font-size: 22px; margin: 0 0 8px; }
.opening-hero p { color: rgba(255,255,255,.82); margin: 4px 0; }
.opening-hero aside { text-align: center; background: rgba(255,255,255,.14); border-radius: 8px; padding: 14px; }
.opening-hero aside span { display: block; opacity: .8; }
.opening-hero aside strong { display: block; font-size: 28px; margin: 4px 0 10px; }
.action-row { display: flex; gap: 12px; margin-bottom: 16px; }
.open-grid { display: grid; grid-template-columns: 1.5fr .8fr; gap: 16px; }
.exception-card p { line-height: 1.9; color: #536078; margin-bottom: 10px; }
@media (max-width: 1000px) { .opening-hero, .open-grid { grid-template-columns: 1fr; } }
</style>
